z=input("Enter a adjective: ")
x=input("Enter a noun: ")
c=input("Enter a plural noun: ")
v=input("Enter a adjective: ")
b=input("Enter a adjective: ")
n=input("Enter a \"ing\" verb: ")
m=input("Enter a \"ing\" verb: ")
l=input("Enter a adjective: ")
k=input("Enter a adjective: ")
j=input("Enter a noun: ")
h=input("Enter a food (plural): ")
g=input("Enter a part of the body (plural): ")
f=input("Enter a adjective: ")
d=input("Enter a vehicle: ")
s=input("Enter a food (plural): ")
a=input("Enter a food (plural): ")
A=input("Enter something alive (plural): ")
S=input("Enter something alive (plural): ")
D=input("Enter a adverb: ")
F=input("Enter a noun: ")

q=("If you go to some " + z + " place like Yellowstone\nNational " + x)
w=("," + " you must know how to deal with the\nwild animals such as bears and wolves and " + c + ".")
e=("\nThe most important of these is the bear.\nThere are three kinds of bear,the grizzly bear,\nthe " + v)
r=(" bear, and the " + b + " bear.\nBears spend most of their time " + n +" or " + m + ".")
t=("\nThey look very " + l + ", but if you make them " + k + ",\nthey might bite your " + j + ".")
y=(" \nBears will come up to your car and beg for " + h + ".")
u=("\nThey will stand on their hind legs and clap their" + g + "\ntogether and pretend to be" + f + ".")
i=("\nBut do not get out of your " + d + " or offer the bears " + s + " or ")
o=(a + "." + "\nThis same advice applies to other wild creatures such as"+ A +" and " + S + ".")
p=("\nRemeber all these rules and you will spend your\nvacation " + D + " and not get eaten by a " + F + ".")



print(q+w+e+r+t+y+u+i+o+p)
